AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for SaaS Feedback Collector backend

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Globals:
  Function:
    Runtime: java17
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: !Sub https://dynamodb.${AWS::Region}.amazonaws.com
        APP_AWS_REGION: !Ref AWS::Region
        DYNAMODB_TABLE: !Ref FeedbackTable

Resources:
  FeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.nextpertis.saasfeedbackcollector.config.AsynchronousLambdaHandler::handleRequest
      CodeUri: target/saasfeedbackcollector-0.0.1-SNAPSHOT.jar
      Events:
        GetFeedbackById:
          Type: Api
          Properties:
            Path: /feedback/{id}
            Method: GET
            RestApiId: !Ref FeedbackApi
        GetFeedbacksByCategory:
          Type: Api
          Properties:
            Path: /feedback
            Method: GET
            RestApiId: !Ref FeedbackApi
        CreateFeedback:
          Type: Api
          Properties:
            Path: /feedback
            Method: POST
            RestApiId: !Ref FeedbackApi
        OptionsMethod:
          Type: Api
          Properties:
            Path: /feedback
            Method: OPTIONS
            RestApiId: !Ref FeedbackApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
                - dynamodb:DescribeTable
              Resource: 
                - !GetAtt FeedbackTable.Arn
                - !Sub "${FeedbackTable.Arn}/index/*"

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Feedback-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  FeedbackApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

Outputs:
  ApiUrl:
    Description: URL of the API endpoint
    Value: !Sub https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  FeedbackTableName:
    Description: DynamoDB Table Name
    Value: !Ref FeedbackTable
  FeedbackTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt FeedbackTable.Arn 