amazon:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:https://dynamodb.eu-north-1.amazonaws.com}
    region: ${APP_AWS_REGION:eu-north-1}
    table-name: ${DYNAMODB_TABLE:Feedback-dev}

logging:
  level:
    org.nextpertis: DEBUG
    com.amazonaws: DEBUG
    